# NOTE: Don't use `sudo` anywhere or the build will run on Travis's slower, outdated build system
language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      jdk: oraclejdk8

jdk:
  - oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - jdk_switcher use oraclejdk8

#
